# Generated by Django 5.0.6 on 2024-07-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysolar',
            name='Hourly_temperature_and_humidity',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='mysolar',
            name='Monthly_Sales',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='mysolar',
            name='Performance',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='mysolar',
            name='Solar_generation',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='mysolar',
            name='Todays_efficiency',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='mysolar',
            name='Weather_prediction',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='mysolar',
            name='Week_revenue',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='mysolar',
            name='inverter_Power_distribution',
            field=models.CharField(max_length=900),
        ),
    ]
