# Generated by Django 5.0.6 on 2024-07-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_app', '0002_alter_mysolar_hourly_temperature_and_humidity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='mysolarrr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(max_length=90)),
                ('production', models.CharField(max_length=80)),
                ('bkk', models.CharField(max_length=90)),
            ],
        ),
        migrations.DeleteModel(
            name='mysolar',
        ),
    ]
