# Generated by Django 5.0.6 on 2024-07-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_app', '0003_mysolarrr_delete_mysolar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysolarrr',
            name='bkk',
            field=models.IntegerField(max_length=90),
        ),
    ]
