# Generated by Django 5.0.6 on 2024-07-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_app', '0004_alter_mysolarrr_bkk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysolarrr',
            name='production',
            field=models.IntegerField(max_length=80),
        ),
        migrations.AlterField(
            model_name='mysolarrr',
            name='total',
            field=models.IntegerField(max_length=90),
        ),
    ]
