# Generated by Django 5.0.7 on 2024-07-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_app', '0009_remove_mysolarrr_bkk_remove_mysolarrr_production_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysolarrr',
            name='Hourly_temperature_and_humidity',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='mysolarrr',
            name='Investor_power_distribution',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='mysolarrr',
            name='Monthly_sales',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='mysolarrr',
            name='Performance',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='mysolarrr',
            name='Solar_generation',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='mysolarrr',
            name='Today_production',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='mysolarrr',
            name='Total_panels',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='mysolarrr',
            name='Weather_prediction',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='mysolarrr',
            name='Weekly_revenue',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
