# Generated by Django 5.0.7 on 2024-07-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_app', '0011_rename_hourly_temperature_and_humidity_mysolarrr_hourly_temperature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysolarrr',
            name='Hourly_temperature',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mysolarrr',
            name='Invertor_power_distribution',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mysolarrr',
            name='Monthly_sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mysolarrr',
            name='Performance',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='mysolarrr',
            name='Solar_generation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mysolarrr',
            name='Today_production',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mysolarrr',
            name='Total_panels',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mysolarrr',
            name='Weather_prediction',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mysolarrr',
            name='Weekly_revenue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mysolarrr',
            name='humidity',
            field=models.IntegerField(default=0),
        ),
    ]
