# Generated by Django 5.0.7 on 2024-07-30 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar_app', '0012_alter_mysolarrr_hourly_temperature_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mysolarrr',
            old_name='Today_production',
            new_name='Daily_production',
        ),
    ]
