# Generated by Django 5.0.7 on 2024-08-01 07:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_app', '0013_rename_today_production_mysolarrr_daily_production'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mysolarrr',
            old_name='Daily_production',
            new_name='daily_production',
        ),
        migrations.RenameField(
            model_name='mysolarrr',
            old_name='Hourly_temperature',
            new_name='hourly_temperature',
        ),
        migrations.RenameField(
            model_name='mysolarrr',
            old_name='Invertor_power_distribution',
            new_name='invertor_power_distribution',
        ),
        migrations.RenameField(
            model_name='mysolarrr',
            old_name='Monthly_sales',
            new_name='monthly_sales',
        ),
        migrations.RenameField(
            model_name='mysolarrr',
            old_name='Solar_generation',
            new_name='solar_generation',
        ),
        migrations.RenameField(
            model_name='mysolarrr',
            old_name='Total_panels',
            new_name='total_panels',
        ),
        migrations.RenameField(
            model_name='mysolarrr',
            old_name='Weather_prediction',
            new_name='weather_prediction',
        ),
        migrations.RenameField(
            model_name='mysolarrr',
            old_name='Weekly_revenue',
            new_name='weekly_revenue',
        ),
        migrations.RemoveField(
            model_name='mysolarrr',
            name='Performance',
        ),
        migrations.AddField(
            model_name='mysolarrr',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mysolarrr',
            name='performance',
            field=models.CharField(default='', max_length=200),
        ),
    ]
