# Generated by Django 5.0.7 on 2024-08-02 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar_app', '0017_event_delete_weekly_data_alter_mysolarrr_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.RemoveField(
            model_name='mysolarrr',
            name='Irradiance',
        ),
        migrations.RemoveField(
            model_name='mysolarrr',
            name='UV_index',
        ),
        migrations.RemoveField(
            model_name='mysolarrr',
            name='efficiency',
        ),
        migrations.RemoveField(
            model_name='mysolarrr',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='mysolarrr',
            name='performance',
        ),
        migrations.RemoveField(
            model_name='mysolarrr',
            name='production',
        ),
        migrations.RemoveField(
            model_name='mysolarrr',
            name='solar_generation',
        ),
        migrations.RemoveField(
            model_name='mysolarrr',
            name='temperature',
        ),
    ]
