# Generated by Django 5.0.7 on 2024-08-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_app', '0018_delete_event_remove_mysolarrr_irradiance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='hourlyspl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solar_generation', models.IntegerField(default=0)),
                ('production', models.IntegerField(default=0)),
                ('temperature', models.IntegerField(default=0)),
                ('performance', models.CharField(default='', max_length=200)),
                ('humidity', models.IntegerField(default=0)),
                ('efficiency', models.IntegerField(default=0)),
                ('UV_index', models.IntegerField(default=0)),
                ('Irradiance', models.IntegerField(default=0)),
            ],
        ),
    ]
