# Generated by Django 5.0.7 on 2024-08-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_app', '0019_hourlyspl'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour_04', models.IntegerField(default=0)),
                ('hour_05', models.IntegerField(default=0)),
                ('hour_06', models.IntegerField(default=0)),
                ('hour_07', models.IntegerField(default=0)),
                ('hour_08', models.IntegerField(default=0)),
                ('hour_09', models.IntegerField(default=0)),
                ('hour_10', models.IntegerField(default=0)),
                ('hour_11', models.IntegerField(default=0)),
                ('hour_12', models.IntegerField(default=0)),
                ('hour_13', models.IntegerField(default=0)),
                ('hour_14', models.IntegerField(default=0)),
                ('hour_15', models.IntegerField(default=0)),
                ('hour_16', models.IntegerField(default=0)),
                ('hour_17', models.IntegerField(default=0)),
                ('hour_18', models.IntegerField(default=0)),
                ('hour_19', models.IntegerField(default=0)),
                ('hour_20', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='hourlyspl',
        ),
    ]
