# Generated by Django 5.0.7 on 2024-08-02 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar_app', '0020_solargeneration_delete_hourlyspl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solargeneration',
            old_name='hour_04',
            new_name='_04_00',
        ),
    ]
