# Generated by Django 5.0.7 on 2024-08-02 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar_app', '0021_rename_hour_04_solargeneration__04_00'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solargeneration',
            old_name='hour_05',
            new_name='_05_00',
        ),
        migrations.RenameField(
            model_name='solargeneration',
            old_name='hour_06',
            new_name='_06_00',
        ),
        migrations.RenameField(
            model_name='solargeneration',
            old_name='hour_07',
            new_name='_07_00',
        ),
        migrations.RenameField(
            model_name='solargeneration',
            old_name='hour_08',
            new_name='_08_00',
        ),
        migrations.RenameField(
            model_name='solargeneration',
            old_name='hour_09',
            new_name='_09_00',
        ),
        migrations.RenameField(
            model_name='solargeneration',
            old_name='hour_10',
            new_name='_10_00',
        ),
        migrations.RenameField(
            model_name='solargeneration',
            old_name='hour_11',
            new_name='_11_00',
        ),
        migrations.RenameField(
            model_name='solargeneration',
            old_name='hour_12',
            new_name='_12_00',
        ),
        migrations.RenameField(
            model_name='solargeneration',
            old_name='hour_13',
            new_name='_13_00',
        ),
        migrations.RenameField(
            model_name='solargeneration',
            old_name='hour_14',
            new_name='_14_00',
        ),
        migrations.RenameField(
            model_name='solargeneration',
            old_name='hour_15',
            new_name='_15_00',
        ),
        migrations.RenameField(
            model_name='solargeneration',
            old_name='hour_16',
            new_name='_16_00',
        ),
        migrations.RenameField(
            model_name='solargeneration',
            old_name='hour_17',
            new_name='_17_00',
        ),
        migrations.RenameField(
            model_name='solargeneration',
            old_name='hour_18',
            new_name='_18_00',
        ),
        migrations.RenameField(
            model_name='solargeneration',
            old_name='hour_19',
            new_name='_19_00',
        ),
        migrations.RenameField(
            model_name='solargeneration',
            old_name='hour_20',
            new_name='_20_00',
        ),
    ]
